# ===================================
# 4. Railway Config (railway.toml) - Root of your project
# ===================================
[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend service
[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.variables]
PORT = "8000"

# Frontend service  
[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.variables]
PORT = "80"